[package]
name = "icc-validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pqcrypto-dilithium = "0.4.5"
iron = "0.5.*"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
